// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ibmuvwlbsibmvfptiacr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlibXV2d2xic2libXZmcHRpYWNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDExMjE3MzYsImV4cCI6MjA1NjY5NzczNn0.UHE40TILy0zzGeUpELx70rdyPAXxxpNlBRvVvJG5oyo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);